#!/bin/bash
#===========================================================================#
#                                                                           #
#          VHestiaCP - Python Functions                                     #
#                                                                           #
#===========================================================================#

# Pyenv directory
export PYENV_ROOT="/opt/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Load pyenv
load_pyenv() {
    if [ -d "$PYENV_ROOT" ]; then
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        return 0
    fi
    return 1
}

# Check if pyenv is installed
is_pyenv_installed() {
    [ -d "$PYENV_ROOT" ] && [ -x "$PYENV_ROOT/bin/pyenv" ]
}

# Check if specific Python version is installed
is_python_version_installed() {
    local version="$1"
    load_pyenv
    pyenv versions --bare 2>/dev/null | grep -q "^${version}"
}

# Get installed Python versions
get_installed_python_versions() {
    load_pyenv
    pyenv versions --bare 2>/dev/null | sort -V
}

# Get default Python version
get_default_python_version() {
    load_pyenv
    pyenv global 2>/dev/null
}

# Install Python version
install_python_version() {
    local version="$1"
    load_pyenv
    
    # Install build dependencies
    apt-get install -y build-essential libssl-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev curl \
        libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
        libffi-dev liblzma-dev 2>/dev/null
    
    pyenv install "$version"
    return $?
}

# Uninstall Python version
uninstall_python_version() {
    local version="$1"
    load_pyenv
    pyenv uninstall -f "$version"
    return $?
}

# Set default Python version
set_default_python_version() {
    local version="$1"
    load_pyenv
    pyenv global "$version"
    return $?
}

# Create virtualenv for a domain
create_python_venv() {
    local user="$1"
    local domain="$2"
    local python_version="$3"
    
    local homedir="${HOMEDIR:-/home}/$user"
    local app_dir="$homedir/web/$domain/pythonapp"
    local venv_dir="$app_dir/venv"
    
    load_pyenv
    
    # Set local Python version
    cd "$app_dir"
    pyenv local "$python_version"
    
    # Create virtualenv
    python -m venv "$venv_dir"
    
    # Upgrade pip
    "$venv_dir/bin/pip" install --upgrade pip
    
    # Install gunicorn
    "$venv_dir/bin/pip" install gunicorn
    
    chown -R "$user:$user" "$venv_dir"
    
    return $?
}

# Install requirements
install_python_requirements() {
    local user="$1"
    local domain="$2"
    
    local homedir="${HOMEDIR:-/home}/$user"
    local app_dir="$homedir/web/$domain/pythonapp"
    local venv_dir="$app_dir/venv"
    local requirements="$app_dir/requirements.txt"
    
    if [ -f "$requirements" ]; then
        runuser -l "$user" -c "cd $app_dir && source venv/bin/activate && pip install -r requirements.txt"
        return $?
    fi
    
    return 0
}

# Get Gunicorn workers count (based on CPU cores)
get_gunicorn_workers() {
    local cores=$(nproc)
    echo $((cores * 2 + 1))
}

# Create Gunicorn config
create_gunicorn_config() {
    local user="$1"
    local domain="$2"
    local port="$3"
    local workers="${4:-$(get_gunicorn_workers)}"
    local app_module="${5:-app:app}"
    
    local homedir="${HOMEDIR:-/home}/$user"
    local conf_dir="$homedir/web/$domain/conf"
    local app_dir="$homedir/web/$domain/pythonapp"
    local log_dir="$homedir/web/$domain/logs"
    local config_file="$conf_dir/gunicorn.conf.py"
    
    mkdir -p "$conf_dir"
    mkdir -p "$log_dir"
    
    cat > "$config_file" << EOF
# Gunicorn configuration for ${domain}
# Generated by VHestiaCP

import multiprocessing

# Server socket
bind = "127.0.0.1:${port}"
backlog = 2048

# Worker processes
workers = ${workers}
worker_class = "sync"
worker_connections = 1000
timeout = 30
keepalive = 2

# Process naming
proc_name = "${domain}"

# Logging
errorlog = "${log_dir}/gunicorn.error.log"
accesslog = "${log_dir}/gunicorn.access.log"
loglevel = "info"
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'

# Server mechanics
daemon = False
pidfile = "${conf_dir}/gunicorn.pid"
user = "${user}"
group = "${user}"
tmp_upload_dir = None

# SSL (if needed, uncomment and configure)
# keyfile = None
# certfile = None
EOF

    chown "$user:$user" "$config_file"
    echo "$config_file"
}

# Create systemd service for Python app
create_python_service() {
    local user="$1"
    local domain="$2"
    local app_module="${3:-app:app}"
    
    local homedir="${HOMEDIR:-/home}/$user"
    local app_dir="$homedir/web/$domain/pythonapp"
    local conf_dir="$homedir/web/$domain/conf"
    local service_name="gunicorn-${user}-${domain//\./-}"
    local service_file="/etc/systemd/system/${service_name}.service"
    
    cat > "$service_file" << EOF
[Unit]
Description=Gunicorn daemon for ${domain}
After=network.target

[Service]
Type=notify
User=${user}
Group=${user}
WorkingDirectory=${app_dir}
Environment="PATH=${app_dir}/venv/bin"
EnvironmentFile=-${app_dir}/.env
ExecStart=${app_dir}/venv/bin/gunicorn \\
    --config ${conf_dir}/gunicorn.conf.py \\
    ${app_module}
ExecReload=/bin/kill -s HUP \$MAINPID
KillMode=mixed
TimeoutStopSec=5
PrivateTmp=true
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    echo "$service_name"
}

# Start Python app
start_python_app() {
    local user="$1"
    local domain="$2"
    
    local service_name="gunicorn-${user}-${domain//\./-}"
    
    systemctl start "$service_name"
    systemctl enable "$service_name"
    return $?
}

# Stop Python app
stop_python_app() {
    local user="$1"
    local domain="$2"
    
    local service_name="gunicorn-${user}-${domain//\./-}"
    
    systemctl stop "$service_name"
    return $?
}

# Restart Python app
restart_python_app() {
    local user="$1"
    local domain="$2"
    
    local service_name="gunicorn-${user}-${domain//\./-}"
    
    systemctl restart "$service_name"
    return $?
}

# Get Python app status
get_python_app_status() {
    local user="$1"
    local domain="$2"
    
    local service_name="gunicorn-${user}-${domain//\./-}"
    
    if systemctl is-active --quiet "$service_name"; then
        echo "running"
    else
        echo "stopped"
    fi
}

# Delete Python app service
delete_python_service() {
    local user="$1"
    local domain="$2"
    
    local service_name="gunicorn-${user}-${domain//\./-}"
    local service_file="/etc/systemd/system/${service_name}.service"
    
    systemctl stop "$service_name" 2>/dev/null
    systemctl disable "$service_name" 2>/dev/null
    rm -f "$service_file"
    systemctl daemon-reload
}

# Detect Python framework
detect_python_framework() {
    local app_dir="$1"
    
    if [ -f "$app_dir/manage.py" ]; then
        echo "django"
    elif grep -q "Flask" "$app_dir/requirements.txt" 2>/dev/null; then
        echo "flask"
    elif grep -q "fastapi" "$app_dir/requirements.txt" 2>/dev/null; then
        echo "fastapi"
    else
        echo "generic"
    fi
}

# Get app module based on framework
get_app_module() {
    local app_dir="$1"
    local framework="$2"
    
    case "$framework" in
        django)
            # Find Django project name
            local project=$(ls -d "$app_dir"/*/ 2>/dev/null | head -1 | xargs basename)
            if [ -n "$project" ]; then
                echo "${project}.wsgi:application"
            else
                echo "config.wsgi:application"
            fi
            ;;
        flask)
            echo "app:app"
            ;;
        fastapi)
            echo "main:app"
            ;;
        *)
            echo "app:app"
            ;;
    esac
}

# Register Python port
register_python_port() {
    local domain="$1"
    local port="$2"
    local ports_file="$HESTIA/data/python_ports.conf"
    
    touch "$ports_file"
    sed -i "/^${domain}:/d" "$ports_file"
    echo "${domain}:${port}" >> "$ports_file"
}

# Unregister Python port
unregister_python_port() {
    local domain="$1"
    local ports_file="$HESTIA/data/python_ports.conf"
    
    if [ -f "$ports_file" ]; then
        sed -i "/^${domain}:/d" "$ports_file"
    fi
}

# Get Python port for domain
get_python_port() {
    local domain="$1"
    local ports_file="$HESTIA/data/python_ports.conf"
    
    if [ -f "$ports_file" ]; then
        grep "^${domain}:" "$ports_file" | cut -d: -f2
    fi
}

# Log function
log_python_event() {
    local level="$1"
    local message="$2"
    local log_file="/var/log/hestia/python.log"
    
    echo "$(date '+%Y-%m-%d %H:%M:%S') [${level}] ${message}" >> "$log_file"
}
